//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBSalesEntities : DbContext
    {
        public DBSalesEntities()
            : base("name=DBSalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_employee> tbl_employee { get; set; }
        public virtual DbSet<tbl_Sales> tbl_Sales { get; set; }
    
        public virtual ObjectResult<sp_allsales_Result> sp_allsales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_allsales_Result>("sp_allsales");
        }
    
        public virtual ObjectResult<sp_manager_Result> sp_manager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_manager_Result>("sp_manager");
        }
    
        public virtual ObjectResult<sp_sales_Result> sp_sales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sales_Result>("sp_sales");
        }
    
        public virtual ObjectResult<sp_salesemp_Result> sp_salesemp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_salesemp_Result>("sp_salesemp");
        }
    }
}
