//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_employee()
        {
            this.tbl_Sales = new HashSet<tbl_Sales>();
        }
    
        public int EmpID { get; set; }
        public string EFirstName { get; set; }
        public string ELastName { get; set; }
        public string Edesignation { get; set; }
        public Nullable<int> EManager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sales> tbl_Sales { get; set; }
    }
}
